const GOOGLE_PLACES_API_KEY = "Insert Key Here";
const ZOMATO_PLACES_API_KEY = "Insert Key Here";
const YELP_PLACES_API_KEY = "Insert Key Here";

export { GOOGLE_PLACES_API_KEY, ZOMATO_PLACES_API_KEY, YELP_PLACES_API_KEY };
